---
- hosts: localhost
  connection: ssh
  become: true
  become_user: ec2-user
  tasks: 
    - name: check whether helm exists or not
      stat:
         path: "/usr/local/bin/helm"
      register: result
    - name: install helm
      command: wget https://get.helm.sh/helm-v3.10.3-linux-amd64.tar.gz
      when: not result.stat.exists
    - name: untar helm
      command: tar -zxvf helm-v3.10.3-linux-amd64.tar.gz
      when: not result.stat.exists
    - name: move helm
      command: sudo mv linux-amd64/helm /usr/local/bin/helm
      when: not result.stat.exists  
    - name: check datree exists or not
      stat:
         path: "/home/ec2-user/.local/share/helm/plugins/helm-datree"
      register: result1
    - name: install helm datree
      command: helm plugin install https://github.com/datreeio/helm-datree
      when: not result1.stat.exists
    - name: update plugin
      command: helm plugin update datree
      when: not result1.stat.exists       

